### ISSUE TITLE
2D Delaunay Filter is misspelled

### ISSUE THREAD

**Issue by banesullivan** [vtkiorg/vtki#118]
The 2D Delaunay filter on the `vtki.PolyData` class is misspelt as `.delauney_2d` which is inconsist with the spelling in VTK and the 3D Delaunay filter under `vtki.DataSetFilters`.

This is leading to confusion among new users. 

I’m afraid this might not be a simple fix by refactoring since `.delauney_2D` filter has been around for a long time and other dependencies might call it.

**Comment by akaszynski** [comment]
Better to fix it now than to let it stick around.  If you think it would be helpful, you can keep the old function, wrap the new correctly spelled one, and add a warning for those still using the old function.

Since ``DeprecationWarning`` is ignored by default, I'd add a general user warning.  Or you can just raise an exception with a helpful error message.

**Comment by banesullivan** [comment]
Good plan. Will implement that soon
